// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC86ECNOVfQst5ioJPG0WWaba3-njEXHUw',
    appId: '1:624813111806:android:00edf1b3652f88aa9de8af',
    messagingSenderId: '624813111806',
    projectId: 'teresa-crm-67199',
    storageBucket: 'teresa-crm-67199.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAldbbfJMIEBeARBzyOVhtVmBJSn9L3g88',
    appId: '1:624813111806:ios:f87aeac240f7dfc49de8af',
    messagingSenderId: '624813111806',
    projectId: 'teresa-crm-67199',
    storageBucket: 'teresa-crm-67199.appspot.com',
    iosBundleId: 'com.example.teresaCustomer',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGz_JGsidAhrGMDg8FzVEAv0Twne4Z-3k',
    appId: '1:624813111806:web:aad81ebb4fe6e7129de8af',
    messagingSenderId: '624813111806',
    projectId: 'teresa-crm-67199',
    authDomain: 'teresa-crm-67199.firebaseapp.com',
    storageBucket: 'teresa-crm-67199.appspot.com',
  );

}